#!/bin/sh
set -e

# Copyright 2024 Robie Basak
# Copyright 2025 Tobias Brox
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Dependencies: /bin/sh, git, basename, dirname. git-annex is supported but not
# required to be installed.
#
# Run from syncthing as:
# syncthing-git %FOLDER_PATH% %FILE_PATH%
#
# The Syncthing folder must be a git working directory (i.e. contain a .git
# directory).  The .git directory should be added to Syncthing's ignore list.


# It doesn't make sense to use the local user's configured name when Syncthing
# is driving it, and this also saves us from dealing with unset name and emails
# that git will complain about.
export GIT_AUTHOR_NAME="syncthing-git"
export GIT_AUTHOR_EMAIL="syncthing-git@example.com"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"

has_parent_component() {
    case "$(basename "$1")" in
        ..) return 0 ;;
        .|/) return 1 ;;
        *)
            has_parent_component "$(dirname "$1")" && return 0
            return 1
        ;;
    esac
}

if [ "$1" = "setup" ]; then
    shift
    exec "$(dirname "$0")/syncthing-git-setup" "$@"
fi

syncthing_dir=$1
file_path=$2

if has_parent_component "$file_path"; then
    echo "Error: $file_path contains .. component" >&2
    exit 1
fi

case "$file_path" in
    .git|.git/*)
        echo "Error: refusing to version file inside .git directory: $file_path" >&2
        exit 1
        ;;
esac

if [ ! -f "$syncthing_dir/$file_path" ]; then
    echo "Error: $syncthing_dir/$file_path isn't a regular file" >&2
    exit 1
fi

cd "$syncthing_dir"
if git config --get annex.uuid >/dev/null; then
    git annex add "./$file_path"
else
    git add "./$file_path"
fi
git_status=$(git status --short --untracked-files=no)
if [ "$git_status" != "" ]; then
    git commit -m"syncthing versioning update"
fi
